const Discord = require("discord.js");
const prefix = '';
// This Was Created For Translate.
langEmbed = new Discord.MessageEmbed().setColor('#171717')
langEmbed
.setTitle("Supported Language Lists 1")
.addField("Here's The Language List. [" + prefix + " lang 2 for page 2]","ID:        Language:")
.addField("af          Afrikaans", "ID:        Language:")
.addField("ak          Akan", "ID:        Language:")
.addField("sq          Albanian", "ID:        Language:")
.addField("am          Amharic", "ID:        Language:")
.addField("ar          Arabic", "ID:        Language:")
.addField("hy          Armenian", "ID:        Language:")
.addField("az          Azerbaijani", "ID:        Language:")
.addField("eu          Basque", "ID:        Language:")
.addField("be          Belarusian", "ID:        Language:")
.addField("bem         Bemba", "ID:        Language:")
.addField("bn          Bengali", "ID:        Language:")
.addField("bh          Bihari", "ID:        Language:")
.addField("bs          Bosnian", "ID:        Language:")
.addField("br          Breton", "ID:        Language:")
.addField("bg          Bulgarian", "ID:        Language:")
.addField("km          Cambodian", "ID:        Language:")
.addField("ca          Catalan", "ID:        Language:")
.addField("chr         Cherokee", "ID:        Language:")
.addField("ny          Chichewa", "ID:        Language:")
.addField("zh-CN       Chinese (Simplified)", "ID:        Language:")
.addField("zh-TW       Chinese (Traditional)", "ID:        Language:")
.addField("co          Corsican", "ID:        Language:")
.addField("hr          Croatian", "ID:        Language:")
.addField("cs          Czech", "ID:        Language:")
.setFooter('Created By Zmacky')

langEmbed2 = new Discord.MessageEmbed().setColor('#171717')
langEmbed2
.setTitle("Supported Language Lists 2")
.addField("Here's The Language List. [" + prefix + " lang 3 for page 3]","ID:        Language:")
.addField("da          Danish", "ID:        Language:")
.addField("nl          Dutch", "ID:        Language:")
.addField("en          English", "ID:        Language:")
.addField("eo          Esperanto", "ID:        Language:")
.addField("et          Estonian", "ID:        Language:")
.addField("ee          Ewe", "ID:        Language:")
.addField("fo          Faroese", "ID:        Language:")
.addField("tl          Filipino", "ID:        Language:")
.addField("fi          Finnish", "ID:        Language:")
.addField("fr          French", "ID:        Language:")
.addField("fy          Frisian", "ID:        Language:")
.addField("gaa         Ga", "ID:        Language:")
.addField("gl          Galician", "ID:        Language:")
.addField("ka          Georgian", "ID:        Language:")
.addField("de          German", "ID:        Language:")
.addField("el          Greek", "ID:        Language:")
.addField("gn          Guarani", "ID:        Language:")
.addField("gu          Gujarati", "ID:        Language:")
.addField("ht          Haitian Creole", "ID:        Language:")
.addField("ha          Hausa", "ID:        Language:")
.addField("haw         Hawaiian", "ID:        Language:")
.addField("iw          Hebrew", "ID:        Language:")
.addField("hi          Hindi", "ID:        Language:")
.addField("hu          Hungarian", "ID:        Language:")
.setFooter('Created By Zmacky')

langEmbed3 = new Discord.MessageEmbed().setColor('#171717')
langEmbed3
.setTitle("Supported Language Lists 3")
.addField("Here's The Language List. [" + prefix + " lang 4 for page 4]","ID:        Language:")
.addField("is          Icelandic", "ID:        Language:")
.addField("ig          Igbo", "ID:        Language:")
.addField("id          Indonesian", "ID:        Language:")
.addField("ia          Interlingua", "ID:        Language:")
.addField("ga          Irish", "ID:        Language:")
.addField("it          Italian", "ID:        Language:")
.addField("ja          Japanese", "ID:        Language:")
.addField("jw          Javanese", "ID:        Language:")
.addField("kn          Kannada", "ID:        Language:")
.addField("kk          Kazakh", "ID:        Language:")
.addField("rw          Kinyarwanda", "ID:        Language:")
.addField("rn          Kirundi", "ID:        Language:")
.addField("kg          Kongo", "ID:        Language:")
.addField("ko          Korean", "ID:        Language:")
.addField("kri         Krio (Sierra Leone)", "ID:        Language:")
.addField("ku          Kurdish", "ID:        Language:")
.addField("ckb         Kurdish (Soranî)", "ID:        Language:")
.addField("ky          Kyrgyz", "ID:        Language:")
.addField("lo          Laothian", "ID:        Language:")
.addField("la          Latin", "ID:        Language:")
.addField("lv          Latvian", "ID:        Language:")
.addField("ln          Lingala", "ID:        Language:")
.addField("lt          Lithuanian", "ID:        Language:")
.setFooter('Created By Zmacky')

langEmbed4 = new Discord.MessageEmbed().setColor('#171717')
langEmbed4
.setTitle("Supported Language Lists 4")
.addField("Here's The Language List. [" + prefix + " lang 5 for page 5]","ID:        Language:")
.addField("loz         Lozi", "ID:        Language:")
.addField("lg          Luganda", "ID:        Language:")
.addField("ach         Luo", "ID:        Language:")
.addField("mk          Macedonian", "ID:        Language:")
.addField("mg          Malagasy", "ID:        Language:")
.addField("ms          Malay", "ID:        Language:")
.addField("ml          Malayalam", "ID:        Language:")
.addField("mt          Maltese", "ID:        Language:")
.addField("mi          Maori", "ID:        Language:")
.addField("mr          Marathi", "ID:        Language:")
.addField("mfe         Mauritian Creole", "ID:        Language:")
.addField("mo          Moldavian", "ID:        Language:")
.addField("mn          Mongolian", "ID:        Language:")
.addField("sr-ME       Montenegrin", "ID:        Language:")
.addField("ne          Nepali", "ID:        Language:")
.addField("pcm         Nigerian Pidgin", "ID:        Language:")
.addField("nso         Northern Sotho", "ID:        Language:")
.addField("no          Norwegian", "ID:        Language:")
.addField("nn          Norwegian (Nynorsk)", "ID:        Language:")
.addField("oc          Occitan", "ID:        Language:")
.addField("or          Oriya", "ID:        Language:")
.addField("om          Oromo", "ID:        Language:")
.addField("ps          Pashto", "ID:        Language:")
.addField("fa          Persian", "ID:        Language:")
.setFooter('Created By Zmacky')


langEmbed5 = new Discord.MessageEmbed().setColor('#171717')
langEmbed5
.setTitle("Supported Language Lists 5")
.addField("Here's The Language List. [" + prefix + " lang 6 for page 6]","ID:        Language:")
.addField("pl          Polish", "ID:        Language:")
.addField("pt-BR       Portuguese (Brazil)", "ID:        Language:")
.addField("pt-PT       Portuguese (Portugal)", "ID:        Language:")
.addField("pa          Punjabi", "ID:        Language:")
.addField("qu          Quechua", "ID:        Language:")
.addField("ro          Romanian", "ID:        Language:")
.addField("rm          Romansh", "ID:        Language:")
.addField("nyn         Runyakitara", "ID:        Language:")
.addField("ru          Russian", "ID:        Language:")
.addField("gd          Scots Gaelic", "ID:        Language:")
.addField("sr          Serbian", "ID:        Language:")
.addField("sh          Serbo-Croatian", "ID:        Language:")
.addField("st          Sesotho", "ID:        Language:")
.addField("tn          Setswana", "ID:        Language:")
.addField("crs         Seychellois Creole", "ID:        Language:")
.addField("sn          Shona", "ID:        Language:")
.addField("sd          Sindhi", "ID:        Language:")
.addField("si          Sinhalese", "ID:        Language:")
.addField("sk          Slovak", "ID:        Language:")
.addField("sl          Slovenian", "ID:        Language:")
.addField("so          Somali", "ID:        Language:")
.addField("es          Spanish", "ID:        Language:")
.addField("es-419      Spanish (Latin American)", "ID:        Language:")
.addField("su          Sundanese", "ID:        Language:")
.setFooter('Created By Zmacky')

langEmbed6 = new Discord.MessageEmbed().setColor('#171717')
langEmbed6
.setTitle("Supported Language Lists 6")
.addField("Here's The Language List. [" + prefix + " lang 7 for page 7]","ID:        Language:")
.addField("sw          Swahili", "ID:        Language:")
.addField("sv          Swedish", "ID:        Language:")
.addField("tg          Tajik", "ID:        Language:")
.addField("tg          Tajik", "ID:        Language:")
.addField("ta          Tamil", "ID:        Language:")
.addField("tt          Tatar", "ID:        Language:")
.addField("te          Telugu", "ID:        Language:")
.addField("th          Thai", "ID:        Language:")
.addField("ti          Tigrinya", "ID:        Language:")
.addField("to          Tonga", "ID:        Language:")
.addField("lua         Tshiluba", "ID:        Language:")
.addField("tum         Tumbuka", "ID:        Language:")
.addField("tr          Turkish", "ID:        Language:")
.addField("tk          Turkmen", "ID:        Language:")
.addField("tw          Twi", "ID:        Language:")
.addField("ug          Uighur", "ID:        Language:")
.addField("uk          Ukrainian", "ID:        Language:")
.addField("ur          Urdu", "ID:        Language:")
.addField("uz          Uzbek", "ID:        Language:")
.addField("vi          Vietnamese", "ID:        Language:")
.addField("cy          Welsh", "ID:        Language:")
.addField("wo          Wolof", "ID:        Language:")
.setFooter('Created By Zmacky')


langEmbed7 = new Discord.MessageEmbed().setColor('#171717')
langEmbed7
.setTitle("Supported Language Lists 7")
.addField("Here's The Language List. [" + prefix + " lang 1 for page 1]","ID:        Language:")
.addField("xh          Xhosa", "ID:        Language:")
.addField("yi          Yiddish", "ID:        Language:")
.addField("yo          Yoruba", "ID:        Language:")
.addField("zu          Zulu", "ID:        Language:")
.setFooter('Created By Zmacky')

module.exports = {
    langEmbed,
    langEmbed2,
    langEmbed3,
    langEmbed4,
    langEmbed5,
    langEmbed6,
    langEmbed7
}